$(document).ready(function() {
    setTimeout(function(){
        $("#manage-id-menu").attr("href","#");
        $("#manage-id-menu").addClass("active");
    },100)
})

$(document).on('shown.lte.pushmenu', function(){
    $("#global-department-name").show();
    $("#global-client-logo").attr("width","100px");
})

$(document).on('collapsed.lte.pushmenu', function(){
    $("#global-department-name").hide();
    $("#global-client-logo").attr("width","40px");
})

$(".modal").on("hidden.bs.modal",function(){
    $(this).find("form").trigger("reset");
})

$(document).on('hidden.bs.modal', '.modal', function () {
    $('.modal.show').length && $(document.body).addClass('modal-open');
});

getUserDetails();
getIdList();
var idIdx;

function getUserDetails(){
    $.ajax({
        type: "POST",
        url: "get-profile-settings.php",
        dataType: 'html',
        data: {
            dummy:"dummy"
        },
        success: function(response){
            var resp = response.split("*_*");
            if(resp[0] == "true"){
                renderUserDetails(resp[1]);
            }else if(resp[0] == "false"){
                alert(resp[1]);
            } else{
                alert(response);
            }
        }
    });
}

function renderUserDetails(data){
    var lists = JSON.parse(data);

    lists.forEach(function(list){
        if(list.image != ""){
            $("#global-user-image").attr("src", list.image);
        }
        $("#global-user-name").text(list.name);
    })

}

function getIdList(){
    $.ajax({
		type: "POST",
		url: "get-id-list.php",
		dataType: 'html',
		data: {
            dummy: "dummy"
		},
		success: function(response){
			var resp = response.split("*_*");
			if(resp[0] == "true"){
				renderIdList(resp[1]);
			}else if(resp[0] == "false"){
				alert(resp[1]);
			} else{
				alert(response);
			}
		}
	});
}

function renderIdList(data){
    var lists = JSON.parse(data);
    var markUp = '<table id="id-table" class="table table-striped table-bordered table-sm">\
                        <thead>\
                            <tr>\
                                <th>ID</th>\
                                <th>Generated By</th>\
                                <th style="max-width:50px;min-width:50px;"></th>\
                            </tr>\
                        </thead>\
                        <tbody>';
    lists.forEach(function(list){
        markUp += '<tr>\
                        <td>'+list.id+'</td>\
                        <td>'+list.generatedby+'</td>\
                        <td>\
                            <div class="dropdown">\
                                <button type="button" data-toggle="dropdown" class="btn btn-success btn-sm dropdown-toggle">More</button>\
                                <ul class="dropdown-menu">\
                                    <li><a href="#" class="pl-2" onclick="deleteId('+list.idx+')"><i class="fas fa-trash"></i> delete</a></li>\
                                </ul>\
                            </div>\
                        </td>\
                   </tr>';
    })
    markUp += '</tbody></table>';
    $("#id-table-container").html(markUp);
    $("#id-table").DataTable();
}

function generateId(){
    $.ajax({
        type: "POST",
        url: "generate-id.php",
        dataType: 'html',
        data: {
            dummy:"dummy"
        },
        success: function(response){
            var resp = response.split("*_*");
            if(resp[0] == "true"){
                renderId(resp[1]);
            }else if(resp[0] == "false"){
                alert(resp[1]);
            } else{
                alert(response);
            }
        }
    });
}

function renderId(id){
    $("#generated-id").text(id);
    $("#generated-id-modal").modal("show");
    getIdList();
}

function deleteId(idx){
    if(confirm("Are you sure you want to delete this ID?This action cannot be undone!")){
        $.ajax({
            type: "POST",
            url: "delete-id.php",
            dataType: 'html',
            data: {
                idx:idx
            },
            success: function(response){
                var resp = response.split("*_*");
                if(resp[0] == "true"){
                    getIdList();
                }else if(resp[0] == "false"){
                    alert(resp[1]);
                } else{
                    alert(response);
                }
            }
        });
    }
}

function logout(){
    $.ajax({
        type: "POST",
        url: "logout.php",
        dataType: 'html',
        data: {
            dummy:"dummy"
        },
        success: function(response){
            var resp = response.split("*_*");
            if(resp[0] == "true"){
                window.open("../../../index.php","_self")
            }else if(resp[0] == "false"){
                alert(resp[1]);
            } else{
                alert(response);
            }
        }
    });
}